### ISSUE TITLE
Issue with modulefile setting the MAALI_LOADED_PRGENV, COMPILER and COMPILER_VER variables

### ISSUE THREAD

**Issue by mshaikh786** [Pawseyops/maali-cygnet#141]
(Tested on chaos-int with modules/3.2.10.6): The modulefile created by maali/1.4.3 is setting the MAALI_LOADED_PRGENV, COMPILER and COMPILER_VER with set command which is not successfully setting the variables outside the scope of brace brackets. Using setenv instead to set the value of the variables does propagate it outside the if condition scope.

**Comment by schibeci** [comment]
This needs to be moved to the maali project.
